### PR TITLE
Adding « Theme Support »

### PR DESCRIPTION
**Pull request by nicolas35380**
Hello,
I propose a (very light) theme selector and the first theme is free ! In fact it's juste a css selector in Settings ;-)

Informations :
1. Each theme must have a json file with 5 field : Name, Description, StyleCss (css file name without .css), LightCss (css file for light variation) and DarkCss (css file for dark variation).
2. Filename of 3 files MUST have the same pattern as yours : xxxx.css, xxxx-light.css and xxxx-dark.css (for compatibility with your darl/light selector)
3. I had to add a new "localizations" : "SettingTheme". Added in en.json and french.json only.
4. New class : Theme. Work really like your Localization class.
5. The new theme is really similar to default. I will update soon ;-)
6. Of course, i tested but I am a really noob with PHP... Maybe the style isn't really nice
7. And i am not a native English speaker ;-)

I hope this will be ok for you.

Nicolas.

### CODE REVIEW

**Comment by Zavy86** [comment]
Hi @nicolas35380, thank you for the pull request.
I was thinking about to develop themes, but if we limit it to the css it would not be very customizable.
I think the template.inc.php file should also be included in the theme.
what do you think about it?

**Comment by Zavy86** [comment]
yes, but I think it is more appropriate to do a big refactoring to the template first in order to provide customizable blocks..
maybe your solution at the moment is the most immediate..
however since it's a "simple override" of the standard css rather than making too many changes in the translation settings etc...
I would suggest a simple way!

@workinprogress

**Comment by Zavy86** [comment]
eventually this `ifs` could be inserted in the Themes.class.php class

> 
> ```
> if(file_exists($APP->PATH.'styles/styles-custom.css')){
>  $style_base=$APP->PATH.'styles/styles-custom.css';
> }else{
>  $style_base=$APP->PATH.'styles/styles.css';
> }
> if(file_exists($APP->PATH.'styles/styles-custom-'.($APP->DARK?"dark":"light").'.css')){
>  $style=$APP->PATH.'styles/styles-custom-'.($APP->DARK?"dark":"light").'.css';
> }else{
>  $style=$APP->PATH.'styles/styles-'.($APP->DARK?"dark":"light").'.css';
> }
> ```
>

**Comment by Zavy86** [comment]
if you want to try to change your pr as suggested otherwise I can work on it next week!

**Comment by Zavy86** [comment]
thinking more about it, custom css can simply be added later to the standards. in this way custom css automatically override standard styles so you can work incrementally and customize just what you want to change..

**Comment by nicolas35380** [comment]
> thinking more about it, custom css can simply be added later to the standards. in this way custom css automatically override standard styles so you can work incrementally and customize just what you want to change..

Even better !

**Comment by Zavy86** [comment]
a single styles-custom.css file..
if exists we include it!
ignored by git..
;)

**Comment by Zavy86** [comment]
> just adding an empty styles-custom.css

it should be specified in the readme..
because if you prepare it then when it updates it will empty.
must be a file ignored by git!

**Comment by Zavy86** [comment]
implemented in version 1.0.4

**Pull request closed without merging**
