### PR TITLE
stops .md direct file access #162

### PR DESCRIPTION
**Pull request by leomoon**
- using apache and nginx
- adds .htaccess
- updates README

There's no need for a user to access the .md files directly.
Editor and viewer must be used...
Other file types should be ok since no one can predict the file names...

### CODE REVIEW

**Comment by leomoon** [comment]
I'm just not sure if we should commit with `.htaccess` or not.

**Comment by ffiesta** [comment]
> This MR is ready.
> 
> I'm just not sure if we should commit with `.htaccess` or not.

Hi, in my opinion now, commit with htacces, this prevent direct access, bu maybe include the base array  
`array("pdf","doc","docx","xls","xlsx","ppt","pptx") and md`.


But in future we need to prevent access to all files, because is bad. I Think some user can uae somo kind of sniffer to find them. And if it private all need to be private.

**Comment by leomoon** [comment]
> > This MR is ready.
> > I'm just not sure if we should commit with `.htaccess` or not.
> 
> Hi, in my opinion now, commit with htacces, this prevent direct access, bu maybe include the base array `array("pdf","doc","docx","xls","xlsx","ppt","pptx") and md`.
> 
> But in future we need to prevent access to all files, because is bad. I Think some user can uae somo kind of sniffer to find them. And if it private all need to be private.

There's no way for someone to figure out the names of attachments...

If we include those in htaccess user won't be able to download pdf for example!

**Comment by ffiesta** [comment]
Hi @leomoon 

You are right "If we include those in htaccess user won't be able to download attachment pdf for example!" 

Commit with bock of md files.

**Comment by Zavy86** [comment]
@leomoon we can just update the setup script to generate the file with this rule and leave the user able to change it if they need?

https://github.com/Zavy86/WikiDocs/blob/master/setup.php#L62

**Comment by leomoon** [comment]
@Zavy86 I've updated the MR.

**Review by Zavy86 — APPROVED** [review]

**Pull request merged**
