### PR TITLE
Ctrl + E shortcut - remove the anchor part of the URL to make the edit link work

### PR DESCRIPTION
**Pull request by OlliL**
When navigating with the TOC, the URL changes and get an anchor (#My_Topic) part added.
Unfortunally, the "?edit" link generated when pressing Ctrl + E does not work with an anchor in front of the query string.
I made a small modification so the anchor part gets removed from the URL before the edit-URL gets generated.
split() will return the string itself if there is no # present at all - so this does not need to be checked beforehand.

### CODE REVIEW

**Comment by Zavy86** [comment]
thank you!

**Review by Zavy86 — COMMENTED** [review]
can you also update the version number?

**Comment by OlliL** [comment]
Yeah of course. Its done.

**Review by Zavy86 — APPROVED** [review]
well done!

**Pull request merged**
