### PR TITLE
Updates all parsedowns

### PR DESCRIPTION
**Pull request by leomoon**
Parsedown 1.7.4
ParsedownExtra 0.8.1
ParsedownExtended 1.2.9
ParsedownFilter 0.0.1
ParsedownPlus 0.0.6

Tested with basic-syntax page and everything looks good.

### CODE REVIEW

**Comment by Zavy86** [comment]
uhm.. I don't remember why, but I had put the 1.8 beta for some reason..
I'll try to remember..

**Comment by Zavy86** [comment]
https://github.com/Zavy86/WikiDocs/commit/85ff30ece094be788fad634c67dbabba2cd7de8f

^

**Comment by leomoon** [comment]
I'll check that out.

**Review by Zavy86 — APPROVED** [review]

**Comment by Zavy86** [comment]
close without merge?

**Comment by leomoon** [comment]
yea there were many issues. seems like what we have is the best combination atm. 😄

**Pull request closed without merging**
