### PR TITLE
Multiple improvements with version bump

### LINKED ISSUE #102: Get Light/Dark mode preference from the browser
### Describe the feature

It would be nice if WikiDoks would honour the preferred light/dark mode setting from the browser.

This would mean people with a dark theme get the dark version, while people with a light theme still get the light version.

### Is your feature request related to a problem? (optional)

_No response_

### Screenshots (optional)

_No response_

### Extra fields

- [ ] I'd like to work on this feature

### PR DESCRIPTION
**Pull request by leomoon**
- Closes #102 
  This will automatically select the correct light/dark theme based on user's os settings.
  Tested by switching my system theme and after refreshing the page, WIkiDocs picked the correct theme.
- Updates Katex to 0.16.10
- Improves nginx configuration in README

This should be good.

### CODE REVIEW

**Comment by leomoon** [comment]
I also added ParsedownPlus to this MR.

This is ready for review.

**Comment by leomoon** [comment]
Also added collapsible section using +++

For example:
```
+++ Collapsible title (optional)
This is the content for the collapsible section. If title is not defined, it will default to: `Click to expand`
+++
```

image

**Comment by Zavy86** [comment]
for the dark parameter removed from the config file, we need to remove also the flag in the settings and in the setup?

**Comment by leomoon** [comment]
Oh yea I missed those two. Updated with rebase.

These two pages will auto change dark/light theme.
image
image

**Review by Zavy86 — DISMISSED** [review]

**Comment by Zavy86** [comment]
This could also be a good idea..

**Comment by leomoon** [comment]
I will remove the themeing part and redo later.

MR is getting messy.

**Comment by leomoon** [comment]
Removed auto theme commit.

Tested with my markdown test page and everything looks ok.
image

**Comment by Zavy86** [comment]
this test page is awesome, can I copy it to wikidocs.it ?

**Review by Zavy86 — APPROVED** [review]

**Comment by leomoon** [comment]
Yea I wanna add more syntax like tables. then I'll have an MR for like `example` page.

**Comment by leomoon** [comment]
So when it is approved, the author of MR should merge? Or we have some other process?

**Comment by Zavy86** [comment]
you can merge! ;)

**Pull request merged**
