### PR TITLE
adds more buttons to the editor

### PR DESCRIPTION
**Pull request by leomoon**
- strikethrough
- code
- table with number of rows/columns
- superscript (No preview. Will render correctly when saved.)
- subscript (No preview. Will render correctly when saved.)
- table of contents (No preview. Will render correctly when saved.)
- recent edits (No preview. Will render correctly when saved.)
- total number of docs (No preview. Will render correctly when saved.)
- undo
- redo

image

### CODE REVIEW

**Review by Zavy86 — DISMISSED** [review]
version bump ;)

**Comment by leomoon** [comment]
Oh damn. I'll add it now.

**Review by Zavy86 — APPROVED** [review]

**Comment by vCoDMods** [comment]
looks like the table of contents  isn´t working, when i add it, blank page

**Comment by leomoon** [comment]
Table of contents will be created for the current doc. You need ot have H1,2,3,4,5,6 in your doc for `[toc]` to generate table of contents.

This:
image

Becomes this:
image

**Comment by vCoDMods** [comment]
@leomoon thanks, didnt knew that. The only problem i see is that Heading is too big now.

**Comment by leomoon** [comment]
I didn't change the heading size. It is what it was.

The TOC is mostly good for really long docs:
image

I don't know how to fix that line yet. Fix might come later.

**Comment by vCoDMods** [comment]
Before it was in one line, now its like 2x bigger 

Screenshot 2024-07-13 023242

**Comment by leomoon** [comment]
The size didn't change.
Before it was continuing and exting over which was causing side menu on some docs to stay open on mobile.
image

Now it wraps longs texts...

**Comment by vCoDMods** [comment]
Yes, i edited it already. I use Custom CSS

Screenshot 2024-07-13 024121

**Comment by leomoon** [comment]
what did you add extactly?

**Comment by vCoDMods** [comment]
> what did you add extactly?
> 
> `h1{font-size:3.5rem;margin:1.75rem 0 1.0rem 0;}` > `h1{font-size:2.5rem;margin:1.75rem 0 1.0rem 0;}`?

yes

**Pull request merged**
