### PR TITLE
three improvements

### PR DESCRIPTION
**Pull request by leomoon**
I could use the styles-custom.css for this but I think this would be a good change for all.
- adds style to scroller bars to make them look more modern
- fixes nav scoller bar going behind .sidenav

desktop light demo:
image

esktop dark demo:
image

mobile demo:
image

### CODE REVIEW

**Comment by Zavy86** [comment]
good! it's possibile to make it works with the theme color variable?

**Review by Zavy86 — APPROVED** [review]

**Comment by leomoon** [comment]
OH YEA I just saw the css var.

I'll update the MR shortly.

**Comment by leomoon** [comment]
This is now using css var

I also added one more commit that adds litteral search with double quotes.

Search with double quotes:
image

Search without double quotes:
image

**Comment by leomoon** [comment]
LOL one more. I just noticed the search text input in dark them is very dark.

This adds lighter text for input#search:
image

**Comment by Zavy86** [comment]
let me know when you are ready for the merge!

**Comment by leomoon** [comment]
I am done for now. It is ready for review. :)

**Review by Zavy86 — APPROVED** [review]

**Pull request merged**
