### PR TITLE
adds multiple security features #211

### PR DESCRIPTION
**Pull request by leomoon**
- adds security headers
- adds better session cookies
- adds session id regeneration to prevent fixation attacks
- restricts katex options to prevent cross-site scripting attacks
- adds KaTeXSecurityFilter to sanitize katex formulas

Running the xss with these changes would replace the xss scripts with BLOCKED which eliminates the attack...
image

Other ppl should also test this.

### CODE REVIEW

**Comment by Zavy86** [comment]
what do you think about renaming the class generically so that we can then use it for all security functions?

**Comment by leomoon** [comment]
yea that works. what should we name it?

**Comment by Zavy86** [comment]
SecurityFilters.class.php ?

**Comment by leomoon** [comment]
This is ready.

**Review by Zavy86 — APPROVED** [review]

**Comment by Zavy86** [comment]
well done!

**Pull request merged**
